INSERT INTO Questions (category_id, question_text)
VALUES
(1, 'Who are the Métis?'),
(2, 'Which party becomes the Official Opposition?'),
(1, 'When is Remembrance Day celebrated?'),
(2, 'What is the highest military honour a Canadian can receive?'),
(3, 'What is a Francophone?'),
(1, 'From where does the name “Canada” come from?'),
(3, 'Give an example of where English and French have equal status in Canada.'),
(2, 'How does a bill become a law?'),
(5, 'Name a responsibility of citizenship.'),
(5, 'Name a right protected by the Canadian Charter of Rights and Freedoms'),
(4, 'What is a territory of Northern Canada and its capital city?'),
(2, 'What are the three levels of government in Canada?'),
(1, 'What are the three main groups of Aboriginal peoples?'),
(2, 'What are the three parts of Parliament?'),
(3, 'What are the two official languages of Canada?'),
(1, 'What did the Canadian Pacific Railway symbolize?'),
(1, 'What did the Fathers of Confederation do?'),
(2, 'What do you call the Sovereign’s representative in the provinces?'),
(5, 'What does the “right to a secret ballot” mean?'),
(2, 'What is Canada’s system of government called?'),
(1, 'What was the “head tax”?'),
(2, 'What is the highest court in Canada?'),
(2, 'What part of the Constitution legally protects the basic rights and freedoms of all Canadians?'),
(1, 'What song is Canada’s national anthem?'),
(1, 'What was the “Underground Railroad”?'),
(1, 'What year did Newfoundland and Labrador join Canada?'),
(2, 'When must federal elections be held?'),
(3, 'Where do most French-speaking Canadians live?'),
(1, 'Which animal is an official symbol of Canada?'),
(6, 'Which of the following is NOT a feature of Canada’s system of government?'),
(1, 'A Member of Parliament from Montreal announces that she will spend her weekend in her electoral district. This means she would be:'),
(1, 'Approximately how many Canadians served in the First World War?'),
(1, 'Fatima is a new immigrant in Canada. What law allows her to take a job at par with a man?'),
(1, 'In the 1960s, Quebec experienced an era of rapid change. What is this called?'),
(1, 'In what industry do most Canadians work?'),
(1, 'What did the Fathers of Confederation do?'),
(1, 'What do you call a law before it is passed?'),
(1, 'What is a major river in Quebec?'),
(1, 'What is the meaning of the Remembrance Day poppy?'),
(1, 'What is the name of the Royal Anthem of Canada?'),
(1, 'What will you promise when you take the Oath of Citizenship?'),
(1, 'When asked, who must you tell how you voted in a federal election?'),
(1, 'When is Remembrance Day celebrated?'),
(1, 'Where are the Parliament Buildings located?'),
(1, 'Which of the following sentences best describes the War of 1812?'),
(1, 'Who has the right to run as a candidate in federal elections?'),
(1, 'Who have major responsibilities on First Nations reserves?'),
(1, 'Who is considered the father of Manitoba?'),
(1, 'Who is the King’s representative in Canada?'),
(1, 'Who led Quebec into Confederation?'),
(1, 'Who was the first Prime Minister of Canada?'),
(1, 'Who were the United Empire Loyalists?'),
(1, 'Who were the Voyagers?'),
(1, 'Why is the battle of Vimy Ridge important?'),
(1, 'What is the capital city of British Columbia?'),
(1, 'What happened at the Battle of the Plains of Abraham?');

-- Level of difficulty: 3 hard, 2 medium, 1 easy
