INSERT INTO Answers (question_id, answer_text, is_correct)
VALUES
(1, 'A distinct people of mixed Aboriginal and European ancestry.', true),
(1, 'Indigenous people from South America.', false),
(1, 'A medieval European religious order.', false),
(1, 'The people of Quebec.', false),
(2, 'The party with the second most MPs.', true),
(2, 'The Green Party.', false),
(2, 'The Libertarian Party.', false),
(2, 'The party with the most MPs.', false),
(3, 'November 11th.', true),
(3, 'May 8th.', false),
(3, 'August 15th.', false),
(3, 'July 1st.', false),
(4, 'Victoria Cross.', true),
(4, 'The Diamond Cross.', false),
(4, 'Medal of honor.', false),
(4, 'The Ruby Medal.', false),
(5, 'A person who speaks French as their first language.', true),
(5, 'A type of French cuisine.', false),
(5, 'A French-speaking city.', false),
(5, 'A term for a French-style phone booth.', false),
(6, 'From "Kanata", the Huron-Iroquois word for village.', true),
(6, 'From the explorer Canadus.', false),
(6, 'It''s a Latin word meaning "Land of the Whales."', false),
(6, 'It is old French for "new world".', false),
(7, 'In certain federal government institutions and documents.', true),
(7, 'In Quebec.', false),
(7, 'In universities across the country.', false),
(7, 'In the Parliament of Canada.', false),
(8, 'Approval by a majority in the House of Commons and Senate and finally the Governor General.', true),
(8, 'By receiving a simple majority vote in the House of Commons.', false),
(8, 'By the Prime Minister''s signature alone.', false),
(8, 'By passing through a series of readings and committees in Parliament.', false),
(9, 'Obeying the law.', true),
(9, 'Attending a citizenship ceremony annually.', false),
(9, 'Paying an additional tax for being a citizen.', false),
(9, 'Serving as a juror in a criminal trial.', false),
(10, 'Aboriginal Peoples'' rights.', true),
(10, 'The right to strike for public sector workers.', false),
(10, 'The right to travel.', false),
(10, 'The right to give notice to an employer.', false),
(11, 'Yukon Territory (Whitehorse).', true),
(11, 'The state of Nunavut with its capital at Inuita.', false),
(11, 'The province of Northern Territories with its capital at Yukon City.', false),
(11, 'The region of Polar North with its capital at Snowtown.', false),
(12, 'Federal, Provincial and Territorial, Municipal (local).', true),
(12, 'Federal, Provincial, and Regional.', false),
(12, 'Central, Local, and Municipal.', false),
(12, 'National, Territorial, and Municipal.', false),
(13, 'First Nations, Métis and Inuit.', true),
(13, 'The Plains Tribes, the Coastal Tribes, and the Northern Tribes.', false),
(13, 'The Algonquian, the Iroquoian, and the Cree.', false),
(13, 'Quebecers, Albertans, and the Ontarians.', false),
(14, 'The Sovereign, the House of Commons and the Senate.', true),
(14, 'The Upper House, the Lower House, and the Prime Minister''s Office.', false),
(14, 'The Senate, the House of Commons, and the Governor General.', false),
(14, 'The House of Lords, the House of Commons, and the Monarch.', false),
(15, 'English and French.', true),
(15, 'English and Latin.', false),
(15, 'English and German.', false),
(15, 'English and Spanish.', false),
(16, 'Unity.', true),
(16, 'It symbolized Canada''s commitment to air travel and modern transportation.', false),
(16, 'It represented Canada''s dedication to space exploration.', false),
(16, 'It symbolized Canada''s passion for maritime trade.', false),
(17, 'They worked together to establish a new country, the Dominion of Canada.', true),
(17, 'They founded the NHL.', false),
(17, 'They established a national banking system.', false),
(17, 'They negotiated trade agreements with European powers.', false),
(18, 'Lieutenant-Governor.', true),
(18, 'The Provincial Ambassador.', false),
(18, 'The Governor General.', false),
(18, 'The Provincial Administrator.', false),
(19, 'No one can watch your vote and no one should look at how you voted.', true),
(19, 'It means citizens can vote via email.', false),
(19, 'It means citizens can vote without showing their identification.', false),
(19, 'It means expats can vote as well.', false),
(20, 'Parliamentary government.', true),
(20, 'The Commonwealth System.', false),
(20, 'The Democratic System.', false),
(20, 'Monarchy.', false),
(21, 'Race-based entry fee charged for Chinese entering Canada.', true),
(21, 'It''s a tax levied on imported hats.', false),
(21, 'It''s a tax on business profits.', false),
(21, 'An immigration tax.', false),
(22, 'The Supreme Court of Canada.', true),
(22, 'The Federal Court of Canada.', false),
(22, 'The Superior Court of Justice.', false),
(22, 'The Supreme Court of Appeals.', false),
(23, 'The Canadian Charter of Rights and Freedoms.', true),
(23, 'The Bill of Rights.', false),
(23, 'First amendment.', false),
(23, 'The Constitutional Rights Act.', false),
(24, 'O Canada.', true),
(24, 'God Save the Queen.', false),
(24, 'Maple Leaf Forever.', false),
(24, 'O Kanadia.', false),
(25, 'An anti-slavery network that helped thousands of slaves escape the United States and settle in Canada.', true),
(25, 'A network of secret tunnels used for smuggling goods.', false),
(25, 'A system of underground shelters for refugees.', false),
(25, 'A clandestine route used by people to escape to freedom into Alaska.', false),
(26, '1949', true),
(26, '1907', false),
(26, '2001', false),
(26, '1968', false),
(27, 'On the third Monday in October every four years following the most recent general election.', true),
(27, 'Every four years on a fixed date.', false),
(27, 'Every six years on a rotating schedule.', false),
(27, 'Whenever the Prime Minister deems necessary.', false),
(28, 'Quebec.', true),
(28, 'In the Maritime provinces.', false),
(28, 'In western Canada.', false),
(28, 'In the province of Quebec and parts of eastern Canada.', false),
(29, 'Beaver.', true),
(29, 'Moose.', false),
(29, 'Elk.', false),
(29, 'Polar Bear.', false),
(30, 'Dictatorship', true),
(30, 'The separation of powers.', false),
(30, 'A bicameral Parliament.', false),
(30, 'A unicameral legislature.', false),
(31, 'In the part of Montreal where she was elected.', true),
(31, 'In her office on Parliament Hill.', false),
(31, 'Visiting the province of Quebec.', false),
(31, 'Going on a vacation.', false),
(32, 'More than 600,000.', true),
(32, '8 million.', false),
(32, '7000.', false),
(32, 'About 60,000.', false),
(33, 'Equality of women and men', true),
(33, 'Equality of all races.', false),
(33, 'Equal pay for equal work.', false),
(33, 'Equal rights.', false),
(34, 'The Quiet Revolution.', true),
(34, 'The Revolution.', false),
(34, 'The West Movement.', false),
(34, 'La Francophonie.', false),
(35, 'Service.', true),
(35, 'Natural resources.', false),
(35, 'Tourism.', false),
(35, 'Manufacturing.', false),
(36, 'They worked together to establish a new country, the Dominion of Canada.', true),
(36, 'They were explorers who formed an expedition to survey Northern Canada.', false),
(36, 'They formed a republic state in Canada.', false),
(36, 'They were a group of politicians that tried to unite Canada to the United States.', false),
(37, 'A Bill.', true),
(37, 'A New law.', false),
(37, 'A Proposed law.', false),
(37, 'A New proposal.', false36),
(38, 'St. Lawrence River.', true),
(38, 'Fraser River.', false),
(38, 'Niagara.', false),
(38, 'Hudson''s Bay.', false),
(39, 'To remember the sacrifice of Canadians who have served or died in wars up to the present day.', true),
(39, 'To remember our Sovereign, Queen Elizabeth II.', false),
(39, 'To celebrate Confederation.', false),
(39, 'To honour Prime Ministers who have died.', false),
(40, 'God Save the Queen (or King).', true),
(40, 'O Canada.', false),
(40, 'The Star-Spangled Banner.', false),
(40, 'La Marseillaise.', false),
(41, 'Pledge allegiance to the King, observe the laws of Canada and fulfil the duties of a Canadian.', true),
(41, 'Pledge to be faithful to the King.', false),
(41, 'Promise to observe the laws of Canada.', false),
(41, 'Fulfil duties as a Canadian citizen.', false),
(42, 'No one.', true),
(42, 'Your employer.', false),
(42, 'A police officer.', false),
(42, 'An Elections Canada official.', false),
(43, 'November 11th.', true),
(43, 'July 1st.', false),
(43, 'October 1st.', false),
(43, 'December 25th.', false),
(44, 'Ottawa.', true),
(44, 'Quebec City.', false),
(44, 'Hull.', false),
(44, 'Toronto.', false),
(45, 'The USA invaded Canada and was defeated, which ensured that Canada would remain independent of the United States.', true),
(45, 'The USA became independent from the British Empire after the war.', false),
(45, 'Napoleon''s fleet was defeated by the Royal Navy in the war.', false),
(45, 'Canada joined the United States after the war.', false),
(46, 'Any Canadian citizen who is at least 18 years old.', true),
(46, 'Anyone.', false),
(46, 'A Canadian citizen who is 16 years old.', false),
(46, 'Any man who is at least 18 years old.', false),
(47, 'Band chiefs and councillors.', true),
(47, 'Municipal governments.', false),
(47, 'Provincial and territorial governments.', false),
(47, 'Federal government.', false),
(48, 'Louis Riel', true),
(48, 'John A. Macdonald', false),
(48, 'Sam Steele', false),
(48, 'Alfred Boyd', false),
(49, 'Governor General of Canada.', true),
(49, 'Prime Minister of Canada.', false),
(49, 'Premier.', false),
(49, 'Lieutenant-Governor.', false),
(50, 'Sir George-Étienne Cartier', true),
(50, 'Sir Louis-Hippolyte La Fontaine', false),
(50, 'Sir Wilfrid Laurier', false),
(50, 'Sir John A. Macdonald', false),
(51, 'Sir John A. Macdonald.', true),
(51, 'Louis Riel.', false),
(51, 'Lester B. Pearson.', false),
(51, 'Abraham Lincoln.', false),
(52, 'Settlers who came to Canada from the United States during the American Revolution.', true),
(52, 'Aboriginal peoples.', false),
(52, 'Métis', false),
(52, 'Inuit.', false),
(53, 'Montreal-based traders who travelled by canoe', true),
(53, 'Immigrants to Canada in the 18th Century', false),
(53, 'Explorers searching for the North-West Passage', false),
(53, 'Geographers who first charted the coastline of British Columbia', false),
(54, 'Canadian Corps secured its reputation for valour and bravery.', true),
(54, 'It was a key position of the German line in Northern Spain.', false),
(54, 'Once Canadians fought at Vimy they knew they would be heading home.', false),
(54, 'It was the "hinge" of the German line as it protected the newly constructed Hindenburg line.', false),
(55, 'Victoria.', true),
(55, 'Vancouver.', false),
(55, 'Prince George.', false),
(55, 'New Westminster.', false),
(56, 'The British defeated the French marking the end of France''s empire in America', true),
(56, 'The Voyagers battled with the British for fur trading rights', false),
(56, 'Americans fought the United Empire Loyalists during the American Revolution', false),
(56, 'The French defeated the British in a battle for Quebec', false);