INSERT INTO Answers (question_id, answer_text, is_correct)
VALUES
(1, 'A distinct people of mixed Aboriginal and European ancestry.', true),
(1, 'Indigenous people from South America.', false),
(1, 'A medieval European religious order.', false),
(1, 'The people of Quebec.', false),
(2, 'The party with the second most MPs.', true),
(2, 'The Green Party.', false),
(2, 'The Libertarian Party.', false),
(2, 'The party with the most MPs.', false),
(3, 'November 11th.', true),
(3, 'May 8th.', false),
(3, 'August 15th.', false),
(3, 'July 1st.', false),
(4, 'Victoria Cross.', true),
(4, 'The Diamond Cross.', false),
(4, 'Medal of honor.', false),
(4, 'The Ruby Medal.', false),
(5, 'A person who speaks French as their first language.', true),
(5, 'A type of French cuisine.', false),
(5, 'A French-speaking city.', false),
(5, 'A term for a French-style phone booth.', false),
(6, 'From "Kanata", the Huron-Iroquois word for village.', true),
(6, 'From the explorer Canadus.', false),
(6, 'It''s a Latin word meaning "Land of the Whales."', false),
(6, 'It is old French for "new world".', false),
(7, 'In certain federal government institutions and documents.', true),
(7, 'In Quebec.', false),
(7, 'In universities across the country.', false),
(7, 'In the Parliament of Canada.', false),
(8, 'Approval by a majority in the House of Commons and Senate and finally the Governor General.', true),
(8, 'By receiving a simple majority vote in the House of Commons.', false),
(8, 'By the Prime Minister''s signature alone.', false),
(8, 'By passing through a series of readings and committees in Parliament.', false),
(9, 'Obeying the law.', true),
(9, 'Attending a citizenship ceremony annually.', false),
(9, 'Paying an additional tax for being a citizen.', false),
(9, 'Serving as a juror in a criminal trial.', false),
(10, 'Aboriginal Peoples'' rights.', true),
(10, 'The right to strike for public sector workers.', false),
(10, 'The right to travel.', false),
(10, 'The right to give notice to an employer.', false),
(11, 'Yukon Territory (Whitehorse).', true),
(11, 'The state of Nunavut with its capital at Inuita.', false),
(11, 'The province of Northern Territories with its capital at Yukon City.', false),
(11, 'The region of Polar North with its capital at Snowtown.', false),
(12, 'Federal, Provincial and Territorial, Municipal (local).', true),
(12, 'Federal, Provincial, and Regional.', false),
(12, 'Central, Local, and Municipal.', false),
(12, 'National, Territorial, and Municipal.', false),
(13, 'First Nations, Métis and Inuit.', true),
(13, 'The Plains Tribes, the Coastal Tribes, and the Northern Tribes.', false),
(13, 'The Algonquian, the Iroquoian, and the Cree.', false),
(13, 'Quebecers, Albertans, and the Ontarians.', false),
(14, 'The Sovereign, the House of Commons and the Senate.', true),
(14, 'The Upper House, the Lower House, and the Prime Minister''s Office.', false),
(14, 'The Senate, the House of Commons, and the Governor General.', false),
(14, 'The House of Lords, the House of Commons, and the Monarch.', false),
(15, 'English and French.', true),
(15, 'English and Latin.', false),
(15, 'English and German.', false),
(15, 'English and Spanish.', false),
(16, 'Unity.', true),
(16, 'It symbolized Canada''s commitment to air travel and modern transportation.', false),
(16, 'It represented Canada''s dedication to space exploration.', false),
(16, 'It symbolized Canada''s passion for maritime trade.', false),
(17, 'They worked together to establish a new country, the Dominion of Canada.', true),
(17, 'They founded the NHL.', false),
(17, 'They established a national banking system.', false),
(17, 'They negotiated trade agreements with European powers.', false),
(18, 'Lieutenant-Governor.', true),
(18, 'The Provincial Ambassador.', false),
(18, 'The Governor General.', false),
(18, 'The Provincial Administrator.', false),
(19, 'No one can watch your vote and no one should look at how you voted.', true),
(19, 'It means citizens can vote via email.', false),
(19, 'It means citizens can vote without showing their identification.', false),
(19, 'It means expats can vote as well.', false),
(20, 'Parliamentary government.', true),
(20, 'The Commonwealth System.', false),
(20, 'The Democratic System.', false),
(20, 'Monarchy.', false),
(21, 'Race-based entry fee charged for Chinese entering Canada.', true),
(21, 'It''s a tax levied on imported hats.', false),
(21, 'It''s a tax on business profits.', false),
(21, 'An immigration tax.', false),
(22, 'The Supreme Court of Canada.', true),
(22, 'The Federal Court of Canada.', false),
(22, 'The Superior Court of Justice.', false),
(22, 'The Supreme Court of Appeals.', false),
(23, 'The Canadian Charter of Rights and Freedoms.', true),
(23, 'The Bill of Rights.', false),
(23, 'First amendment.', false),
(23, 'The Constitutional Rights Act.', false),
(24, 'O Canada.', true),
(24, 'God Save the Queen.', false),
(24, 'Maple Leaf Forever.', false),
(24, 'O Kanadia.', false),
(25, 'An anti-slavery network that helped thousands of slaves escape the United States and settle in Canada.', true),
(25, 'A network of secret tunnels used for smuggling goods.', false),
(25, 'A system of underground shelters for refugees.', false),
(25, 'A clandestine route used by people to escape to freedom into Alaska.', false),
(26, '1949', true),
(26, '1907', false),
(26, '2001', false),
(26, '1968', false),
(27, 'On the third Monday in October every four years following the most recent general election.', true),
(27, 'Every four years on a fixed date.', false),
(27, 'Every six years on a rotating schedule.', false),
(27, 'Whenever the Prime Minister deems necessary.', false),
(28, 'Quebec.', true),
(28, 'In the Maritime provinces.', false),
(28, 'In western Canada.', false),
(28, 'In the province of Quebec and parts of eastern Canada.', false),
(29, 'Beaver.', true),
(29, 'Moose.', false),
(29, 'Elk.', false),
(29, 'Polar Bear.', false),
(30, 'Dictatorship', true),
(30, 'The separation of powers.', false),
(30, 'A bicameral Parliament.', false),
(30, 'A unicameral legislature.', false);
