DROP TABLE IF EXISTS questions CASCADE;
CREATE TABLE "questions" (
  "question_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" int,
  "question_text" text NOT NULL,
  "question_difficulty" int
);