DROP TABLE IF EXISTS answers CASCADE;
CREATE TABLE "answers" (
  "answer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_id" int,
  "answer_text" text NOT NULL,
  "is_correct" boolean
);