DROP TABLE IF EXISTS userProgress CASCADE;
CREATE TABLE "userProgress" (
  "progress_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "question_id" int,
  "is_answered" boolean,
  "user_answer_id" int
);